import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import { TransactionProvider } from "@/components/transaction-provider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <TransactionProvider>
          <Navbar />
          <div className="flex overflow-hidden">
            <Sidebar />
            <main className="w-full flex-1 bg-muted-foreground/10 h-screen">
              {children}
            </main>
          </div>
        </TransactionProvider>
      </body>
    </html>
  );
}
